name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gcc -o hello.o hello.c
      run: gcc -o hello.o hello.c
    - name: commands
      rund: ./hello.o Gabriele

